package com.sysone.ogamza.sql.admin;

public class NotificationSql {
    public static final String GET_NULL_EMPLOYEE_ID_ACCESS_LOG_COUNT = "SELECT COUNT(*) FROM ACCESS_LOG WHERE EMPLOYEE_ID IS NULL AND IS_READ = 0";
    public static final String GET_NULL_EMPLOYEE_ID_ACCESS_TIMES = "SELECT ACCESS_TIME FROM ACCESS_LOG WHERE EMPLOYEE_ID IS NULL AND IS_READ = 0 ORDER BY ACCESS_TIME DESC";
    public static final String MARK_UNAUTHORIZED_ACCESS_LOG_AS_READ = "UPDATE ACCESS_LOG SET IS_READ = 1 WHERE EMPLOYEE_ID IS NULL AND IS_READ = 0";
}